<script>

	import SignInForm from "$lib/components/forms/sign-in.svelte";
  import HeroImg from '$lib/assets/hero-generate-image.png'
</script>
<div class="hero h-full max-lg:bg-[url('$lib/assets/hero-generate-image.png')] lg:bg-base-100 relative">
  <span class="inline-flex absolute bottom-1 left-1 text-sm text-neutral-content/70">* Image generated by Pixrl, because we are developers...</span>
  <div class="hidden lg:block h-full w-1/2 place-self-start ">
    <img src={HeroImg} alt="dashboard" class="w-full h-full object-cover">
  </div>
    <div class="hero-content flex-col lg:place-self-end lg:h-full lg:w-1/2 lg:bg-base-200">
      <div class=" text-pretty prose dark:prose-invert">
        <h1 class="">SEO kit</h1>
        <h3>Some lovely text regarding how amazing our app is</h3>
      </div>
      <div class="card shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
        
          <SignInForm />
        <div class="card-body pt-0">
            <div class="divider mt-0">or</div>
            <a href="/get-started?activeTab=register" class="btn text-primary">Sign Up</a>
        </div>
        <a href="/dashboard">Continue to Dashboard</a>
      </div>
    </div>
  </div>